version: '3.8'

services:
  moderation:
    build:
      context: .
      dockerfile: cmd/moderation/Dockerfile
    depends_on:
      - db
    environment:
      - CONFIG_PATH=/configs/config.yaml
    volumes:
      - ./configs:/configs
      - ./.env:/.env

  analytics:
    build:
      context: .
      dockerfile: cmd/analytics/Dockerfile
    environment:
      - CONFIG_PATH=/configs/config.yaml
    volumes:
      - ./configs:/configs
      - ./.env:/.env

  automation:
    build:
      context: .
      dockerfile: cmd/automation/Dockerfile
    environment:
      - CONFIG_PATH=/configs/config.yaml
    volumes:
      - ./configs:/configs
      - ./.env:/.env

  user_management:
    build:
      context: .
      dockerfile: cmd/user_management/Dockerfile
    environment:
      - CONFIG_PATH=/configs/config.yaml
    volumes:
      - ./configs:/configs
      - ./.env:/.env

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=telegram_bot
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: