version: '3.8'

services:
  moderation:
    build:
      context: .
      dockerfile: cmd/moderation/Dockerfile
    depends_on:
      - db
    environment:
      - CONFIG_PATH=/configs/config.yaml
    env_file:
      - .env
    volumes:
      - ./configs:/configs

  automation:
    build:
      context: .
      dockerfile: cmd/automation/Dockerfile
    environment:
      - CONFIG_PATH=/configs/config.yaml
    env_file:
      - .env
    volumes:
      - ./configs:/configs

  analytics:
    build:
      context: .
      dockerfile: cmd/analytics/Dockerfile
    environment:
      - CONFIG_PATH=/configs/config.yaml
    env_file:
      - .env
    volumes:
      - ./configs:/configs

  user_management:
    build:
      context: .
      dockerfile: cmd/user_management/Dockerfile
    environment:
      - CONFIG_PATH=/configs/config.yaml
    env_file:
      - .env
    volumes:
      - ./configs:/configs

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: